name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202
    - name: Echo ref
      run: |
        echo ref ${{ github.ref }}
        echo head ref ${{ github.head_ref }}
    - name: Package build (ubuntu)
      if: startsWith(matrix.os, 'ubuntu')
      run: ./build.sh --target=Zip
    - name: Package build (windows)
      if: startsWith(matrix.os, 'windows')
      run: ./build.ps1 -target Zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: '*.zip'
  create-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
      - run: yarn
      - run: yarn semantic-release --ci