name: Documentation

on: [push]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.202
    - name: Setup Node.js
      uses: actions/setup-node@v1.4.2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Install standard-changelog
      run: npm i -g standard-changelog
    - name: Install mkdocs
      run: pip install mkdocs mkdocs-material
    - name: Build documentation
      run: ./build.sh --target=Docs
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.0
      with:
        build_dir: site
      env: 
        GITHUB_TOKEN: ${{ github.token }}
